#!/usr/bin/env zsh

# Check if 'kubectl' command exists
if command -v kubectl &> /dev/null; then
    # Get the active kubectl context
    context=$(kubectl config current-context 2>/dev/null)

    if [[ -n "$context" ]]; then
        echo "[k8s: $context] "
    else
        echo ""
    fi
else
    echo ""
fi