#!/usr/bin/env zsh
# Calculate a session name based on the path provided
# home: ~
# root: /
# opt: ~/opt
# ~/{}: ~/**
# /{}: /**

# Function to get the absolute directory from a file or directory path
get_absolute_directory() {
  local path
  # Resolve the path to an absolute path
  path="${1:a}"

  if [[ -d $path ]]; then
    echo $path
  elif [[ -f $path ]]; then
    dirname $path
  else
    return 1
  fi
}

# Function to assign value based on directory
derive_name() {
  local dir=$1
  case $dir in
    ~ | $HOME)
      echo "home"
      ;;
    /)
      echo "root"
      ;;
    $HOME/opt)
      echo "opt"
      ;;
    $HOME/*)
      echo "~/${dir#$HOME/}"
      ;;
    /*)
      echo "/${dir#/}"
      ;;
    *)
      return 1
      ;;
  esac
}

# Main script logic
local input_path=$1
[[ -z "$input_path" ]] && return 1

absolute_directory=$(get_absolute_directory $input_path) || return 1
value=$(derive_name $absolute_directory) || return 1
echo "$value"