#!/usr/bin/env zsh
# Calculate a session name based on the path provided
# home: ~
# root: /
# opt: ~/opt
# ~/{}: ~/**
# /{}: /**

local input_name=$1
[[ -z "$input_name" ]] || return 1

case $input_name in
  home)
    echo "~"
    ;;
  root)
    echo "/"
    ;;
  opt)
    echo "~/opt"
    ;;
  *)
    echo "${input_name}"
    ;;
esac