#!/usr/bin/env zsh
# Calculate a session name based on the path provided
# home: ~
# root: /
# opt: ~/opt
# ~/{}: ~/**
# /{}: /**

# Function to get the absolute directory from a file or directory path
get_absolute_directory() {
  local path
  # Resolve the path to an absolute path
  path="${1:a}"

  if [[ -d $path ]]; then
    echo $path
  elif [[ -f $path ]]; then
    dirname $path
  else
    echo ""
  fi
}

# Function to assign value based on directory
get_value() {
  local dir=$1
  case $dir in
    ~ | $HOME)
      echo "home"
      ;;
    /)
      echo "root"
      ;;
    $HOME/opt)
      echo "opt"
      ;;
    $HOME/*)
      echo "~/${dir#$HOME/}"
      ;;
    /*)
      echo "/${dir#/}"
      ;;
    *)
      echo ""
      ;;
  esac
}

# Main script logic
local input_path=$1
if [[ -z "$input_path" ]]; then
  echo ""
  return 1
fi

absolute_directory=$(get_absolute_directory $input_path)

if [[ -z $absolute_directory ]]; then
  echo ""
  return 1
else
  value=$(get_value $absolute_directory)
  [[ -n $value ]] && echo "${value}" || echo ""
fi