LOADKEYS="us"
TIMEZONE="America/Los_Angeles"

OS_HOST_DRIVE="/dev/nvme1n1"
BOOT_PARTITION="${OS_HOST_DRIVE}p1"
ROOT_PARTITION="${OS_HOST_DRIVE}p2"
DATA_PARTITION="${OS_HOST_DRIVE}p3"
SWAP_PARTITION="${OS_HOST_DRIVE}p4"
HOME_PARTITION="${OS_HOST_DRIVE}p5"