#!/bin/env zsh

local name="$1"
shift
local paths=("$@")

local path
for path in "${paths[@]}"; do

  local expanded_paths=($path)
  for expanded_path in "${expanded_paths[@]}"; do
    if [[ -d "$expanded_path" ]]; then
      export $name="$expanded_path"
      break 2
    fi
  done
done