# load settings from the ~/env/configs/zsh/settings folder
load_setting general
load_setting suggestions
load_setting highlighting
load_setting history

load_setting app_rc

load_setting comp

load_setting aliases
load_setting prompt
