#!/usr/bin/env zsh

# Usage: dotenv_update_value FILE KEY VALUE [separator]
# Example: dotenv_update_value apps/web/.env.local AWS_REGION us-east-1 "#"
# runs `sed -i '' 's#AWS_REGION=.*$#AWS_REGION=us-east-1#g' apps/web/.env.local`

# Check for the correct number of arguments
if (( $# < 3 )) || (( $# > 4 )); then
  echo "Usage: dotenv_update_value FILE KEY VALUE [separator]"
  return 1
fi

local file=$1
local key=$2
local value=$3
local separator=${4:-"/"}  # Default separator is '/'

# Check if the provided file exists
if [[ ! -f $file ]]; then
  echo "Error: File '$file' does not exist."
  return 1
fi

# Prepare the sed command pattern
local pattern="s${separator}${key}=.*${separator}${key}=${value}${separator}g"
# Below is preferred but needs to be tested
# local pattern="s${separator}${key}=.*\$${separator}${key}=${value}${separator}g"

# Use the appropriate sed command based on the operating system
if os_is_macos; then
  sed -i '' "$pattern" "$file"
elif os_is_linux; then
  sed -i "$pattern" "$file"
else
  echo "Error: Unsupported operating system."
  return 1
fi