start-at-login = true

# RED_PASTEL: #ff0880
after-login-command = []
after-startup-command = [
  # 'exec-and-forget borders inactive_color=0x00000000 active_color=0x20aaaaaa width=10 hidpi=on',
  # 'exec-and-forget sketchybar',
]

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 0

default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Doesn't work on macOS
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']
automatically-unhide-macos-hidden-apps = true

# See https://nikitabobko.github.io/AeroSpace/guide#key-mapping
[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 10
inner.vertical =   10
outer.left =       10
outer.bottom =     10
outer.top =        10
outer.right =      10

# 'main' binding mode declaration
[mode.main.binding]

# Disable CMD+h
cmd-h = [] # Disable "hide application"
cmd-alt-h = [] # Disable "hide others"

# Reload config
alt-shift-r = 'reload-config'

# See: https://nikitabobko.github.io/AeroSpace/commands#layout
alt-shift-slash = 'layout tiles horizontal vertical'
alt-shift-comma = 'layout accordion horizontal vertical'

# See: https://nikitabobko.github.io/AeroSpace/commands#focus
alt-left = 'focus left --boundaries-action wrap-around-the-workspace'
alt-down = 'focus down --boundaries-action wrap-around-the-workspace'
alt-up = 'focus up --boundaries-action wrap-around-the-workspace'
alt-right = 'focus right --boundaries-action wrap-around-the-workspace'

# See: https://nikitabobko.github.io/AeroSpace/commands#move
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

# Fullscreen
alt-f = 'fullscreen'

# See: https://nikitabobko.github.io/AeroSpace/commands#resize
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace
alt-shift-m = """
exec-and-forget \
  aerospace list-workspaces \
  --monitor focused \
  --empty no \
  | aerospace workspace next \
  --wrap-around
"""

alt-shift-n = """
exec-and-forget \
  aerospace list-workspaces \
  --monitor focused \
  --empty no \
  | aerospace workspace prev \
  --wrap-around
"""

alt-f1 = 'workspace 1'
alt-f2 = 'workspace 2'
alt-f3 = 'workspace 3'
alt-f4 = 'workspace 4'
alt-f5 = 'workspace 5'
alt-f6 = 'workspace 6'
alt-f7 = 'workspace 7'
alt-f8 = 'workspace 8'
alt-f9 = 'workspace 9'

# See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
alt-shift-f1 = 'move-node-to-workspace 1'
alt-shift-f2 = 'move-node-to-workspace 2'
alt-shift-f3 = 'move-node-to-workspace 3'
alt-shift-f4 = 'move-node-to-workspace 4'
alt-shift-f5 = 'move-node-to-workspace 5'
alt-shift-f6 = 'move-node-to-workspace 6'
alt-shift-f7 = 'move-node-to-workspace 7'
alt-shift-f8 = 'move-node-to-workspace 8'
alt-shift-f9 = 'move-node-to-workspace 9'

# See: https://nikitabobko.github.io/AeroSpace/commands#workspace-back-and-forth
alt-tab = 'workspace-back-and-forth'
# See: https://nikitabobko.github.io/AeroSpace/commands#move-workspace-to-monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'


