name: <%= @settings["workspace"] %>
root: <%= @settings["workspace"] %>

windows:
  - ide:
      layout: main-horizontal
      panes:
        - nvim .
        - null
  - git:
      panes:
        - lazygitt
  - tasks:
      panes:
        - null
