[general]
live_config_reload = true

[window]
opacity = 0.75
blur = true
startup_mode = "Maximized"
decorations = "Buttonless"
option_as_alt = "Both"
dynamic_padding = true

[font.normal]
family = "MonaspiceKr Nerd Font Mono"
style = "Regular"

[font.bold]
family = "MonaspiceNe Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Regular"

[font.bold_italic]
family = "MonaspiceRn Nerd Font Mono"
style = "Bold"

[colors]
transparent_background_colors = true

[colors.hints.start]
foreground = "#000000"
background = "#FFFFFF"

