#!/usr/bin/env zsh

# Check if a path is under the home directory and convert to ~ if it is
normalize_path() {
  local path="$1"
  [[ "$path" == "$HOME"* ]] && echo "~${path#$HOME}" || echo "$path"
}

# Resolve path to absolute path
get_absolute_path() {
  local path="$1"
  (cd "$path" && pwd -P)
}

# Main function to calculate and display the normalized path
get_normalized_path() {
  local path="${1:-$PWD}"
  [[ "$path" != /* && "$path" != ~* ]] && path="$PWD/$path"
  local absolute_path=$(get_absolute_path "$path")
  echo $(normalize_path "$absolute_path")
}

get_normalized_path "$1"